name: Terraform Module Docs Test
on:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout."
        required: false
        default: main
        type: string
      dir:
        description: "The directory the modules are contained within."
        required: false
        default: modules
        type: string
      git-commit-message:
        description: "The message used by git when committing."
        required: false
        default: "chore: auto update README.md files"
        type: string
jobs:
  update-readme:
    name: Update README.md files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ inputs.ref }}

      - name: Render Terraform docs and commit changes
        uses: terraform-docs/gh-actions@v1
        with:
          find-dir: ${{ inputs.dir }}
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: ${{ inputs.git-commit-message }}
